---
all:
  children:
    proxmox_x86_cluster:
      vars:
        cluster_name: pve-x86
        primary_node: x86-node-01
      hosts:
        x86-node-01:
          ansible_host: 10.0.0.3
          ansible_user: root
          proxmox_api_password: "{{ lookup('env', 'X86_NODE_01_SSH_PASS') }}"
          ssm_tailscale_authkey_path: "/homelab/proxmox-node-management/x86-node-01-auth-key"
          os_disk: /dev/disk/by-id/nvme-WD_BLACK_SN770M_2TB_255212800414
          vmdata_disk: /dev/disk/by-id/nvme-Samsung_SSD_990_PRO_4TB_S7KGNJ0WB00297R
        x86-node-02:
          ansible_host: 10.0.0.4
          ansible_user: root
          proxmox_api_password: "{{ lookup('env', 'X86_NODE_02_SSH_PASS') }}"
          ssm_tailscale_authkey_path: "/homelab/proxmox-node-management/x86-node-02-auth-key"
          os_disk: /dev/disk/by-id/ata-Samsung_SSD_850_EVO_250GB_S21NNSAFC65434J
          vmdata_disk: /dev/disk/by-id/nvme-Samsung_SSD_9100_PRO_with_Heatsink_4TB_S7ZRNJ0Y504262D


    proxmox_arm_cluster:
      hosts:
    # rpi5:
    #   ansible_host: 10.0.1.20

    # Proxmox nodes (all clusters)
    proxmox_nodes:
      children:
        proxmox_x86_cluster:
        proxmox_arm_cluster:
      vars:
        tailscale_login_server: "https://headscale.levizitting.com"
        tailscale_advertise_routes: "10.0.0.0/24"

    bootstrap:
      vars:
        ansible_ssh_user: root
        management_gateway: 10.0.0.1
        management_vlan: 11
      hosts:
        x86-node-01:
          ansible_ssh_pass: "{{ lookup('env', 'X86_NODE_01_SSH_PASS') }}"
        x86-node-02:
          ansible_ssh_pass: "{{ lookup('env', 'X86_NODE_02_SSH_PASS') }}"
  vars:
    ansible_ssh_private_key_file: ""
    ansible_ssh_use_ssh_agent: true
